apiVersion: v1
kind: Service
metadata:
  name: syncfusion-dash
  labels:
    app: syncfusion-dash
    env: test

spec:
  type: NodePort
  selector:
    app: syncfusion-dash
    env: test
  ports:
    - port: 3050
      targetPort: 3000
      protocol: TCP
      nodePort: 31000