apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncfusion-dash-backend
  labels:
    app: syncfusion-dash-backend
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncfusion-dash-backend
      env: test
    
  template:
    metadata:
      name: syncfusion-dash-backend
      labels:
        app: syncfusion-dash-backend
        env: test
    
    spec:
      containers:
      - name: scalable-syncfusion-dashboard
        image: ayushbehl31/scalable_backend_img:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"

          limits:
            memory: "4Gi"
            cpu: "1500m"